export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as ShoppingCart } from "./Account/ShoppingCart";
export { default as NotFound } from "./NotFound";
export { default as Login } from "./Auth/Login";
export { default as Register } from "./Auth/Register";
export { default as ForgotPassword } from "./Auth/ForgotPassword";
export { default as ResetPassword } from "./Auth/ResetPassword";
